# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tor_requests 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "tor_requests".freeze
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Bruno Ghisi".freeze]
  s.date = "2023-06-30"
  s.description = "Create anonymously requests through Tor network".freeze
  s.email = "brunogh@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/tor/configuration.rb",
    "lib/tor/http.rb",
    "lib/tor/tor_requests.rb",
    "lib/tor_requests.rb",
    "spec/configuration_spec.rb",
    "spec/http_spec.rb",
    "spec/integration_spec.rb",
    "spec/spec_helper.rb",
    "tor_requests.gemspec"
  ]
  s.homepage = "http://github.com/brunogh/tor_requests".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.1".freeze
  s.summary = "Create anonymously requests through Tor network".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<bundler>.freeze, ["~> 2.4"])
  s.add_development_dependency(%q<byebug>.freeze, ["~> 11.1"])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.5"])
  s.add_development_dependency(%q<rspec>.freeze, ["~> 3.12"])
  s.add_development_dependency(%q<rubocop>.freeze, ["~> 1.53"])
  s.add_development_dependency(%q<rubocop-rspec>.freeze, ["~> 2.22"])
  s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.22.0"])
  s.add_development_dependency(%q<socksify>.freeze, ["~> 1.7"])
  s.add_development_dependency(%q<webmock>.freeze, ["~> 3.13"])
  s.add_runtime_dependency(%q<socksify>.freeze, [">= 0"])
end

